name: Example GCP Auth

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  gcp-auth-example:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Authenticate to Google Cloud
        uses: mt0pps/tf-gcp-workflow-templates/.github/actions/gcp-auth@main
        with:
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4

      - name: Verify GCP Access
        run: |
          gcloud auth list
          gcloud projects describe ${{ vars.GCP_PROJECT_ID }}
